UPDATE widgets SET details_uri='https://icenter.bakerhughes.com/trpCasesPage' WHERE id=9;
UPDATE widgets SET details_uri='https://icenter.bakerhughes.com/waterWash?vid=<VID>' WHERE id=10;
UPDATE widgets SET details_uri='https://icenter.bakerhughes.com/fca?vid=<VID>' WHERE id=11;
UPDATE widgets SET details_uri='https://icenter.bakerhughes.com/thrustLoad?vid=<VID>&from=<FROM_DATE>&to=<TO_DATE>' WHERE id=15;
UPDATE widgets SET details_uri='https://icenter.bakerhughes.com/thrustLoad?vid=<VID>&from=<FROM_DATE>&to=<TO_DATE>' WHERE id=16;
UPDATE widgets SET details_uri='https://icenter.bakerhughes.com/thrustLoad?vid=<VID>&from=<FROM_DATE>&to=<TO_DATE>' WHERE id=17;
UPDATE widgets SET details_uri='https://icenter.bakerhughes.com/thrustLoad?vid=<VID>&from=<FROM_DATE>&to=<TO_DATE>' WHERE id=18;
UPDATE widgets SET details_uri='https://icenter.bakerhughes.com/thrustLoad?vid=<VID>&from=<FROM_DATE>&to=<TO_DATE>' WHERE id=35;
UPDATE widgets SET details_uri='https://icenter.bakerhughes.com/thrustLoad?vid=<VID>&from=<FROM_DATE>&to=<TO_DATE>' WHERE id=36;
UPDATE widgets SET details_uri='https://icenter.bakerhughes.com/spinningReserve?vid=<VID>&from=<FROM_DATE>&to=<TO_DATE>' WHERE id=19;
UPDATE widgets SET details_uri='https://icenter.bakerhughes.com/spinningReserve?vid=<VID>&from=<FROM_DATE>&to=<TO_DATE>' WHERE id=20;
UPDATE widgets SET details_uri='https://icenter.bakerhughes.com/dleHealthStatus?vid=<VID>&from=<FROM_DATE>&to=<TO_DATE>' WHERE id=22;
UPDATE widgets SET details_uri='https://icenter.bakerhughes.com/ceco-analysis?vid=<VID>&from=<FROM_DATE>&to=<TO_DATE>' WHERE id IN (12,13,14);
UPDATE widgets SET details_uri='https://icenter.bakerhughes.com/carbonOptimizer?vid=<VID>' WHERE id=-38;
UPDATE widgets SET details_uri='https://icenter.bakerhughes.com/carbonOptimizer?vid=<VID>' WHERE id=-21;
UPDATE widgets SET details_uri='https://icenter.bakerhughes.com/carbonOptimizer?vid=<VID>' WHERE id=21;
UPDATE widgets SET details_uri='https://icenter.bakerhughes.com/carbonOptimizer?vid=<VID>' WHERE id=38;
UPDATE widgets SET details_uri='https://icenter.bakerhughes.com/maintenanceOptimizer?vid=<VID>&service=MO' WHERE id=-31;
UPDATE widgets SET details_uri='https://icenter.bakerhughes.com/maintenanceOptimizer?vid=<VID>&service=MO' WHERE id=-3;
UPDATE widgets SET details_uri='https://icenter.bakerhughes.com/maintenanceOptimizer?vid=<VID>&service=MO' WHERE id=3;
UPDATE widgets SET details_uri='https://icenter.bakerhughes.com/maintenanceOptimizer?vid=<VID>&service=HI' WHERE id=23;
UPDATE widgets SET details_uri='https://icenter.bakerhughes.com/maintenanceOptimizer?vid=<VID>&service=HI' WHERE id=24;
UPDATE widgets SET details_uri='https://icenter.bakerhughes.com/waterWash?vid=<VID>' WHERE id=37;

UPDATE widgets SET status_id=2 WHERE id IN (30,31);